Task 2-5までとOptional完了
dai08/householdkeep pull request #2
Opened 2023-04-13 08:16 UTC by dai08

##詳細
テーブルの本実装
・テーブルの実装をしました。
フォームの充実
・フォームの日付をプルダウンで表示出来るようにしました。
・食費、固定費をプルダウンで表示出来るようにしました。
・選択した日付と費用（食費または固定費）と金額を、反映ボタンを押すことでテーブルに反映するようにしました。
Optional
・テーブルの日付をクリックすると該当する日付がプルダウンで表示された状態のフォームを表示出来るようにしました。

・フォームの反映ボタンを押すとテーブルに切り替わるようにしました。
##画面キャプチャ
![スクリーンショット 2023-04-13 17 14 24](https://user-images.githubusercontent.com/38682085/231697311-5cf110ae-aba2-4a4f-933a-058587035e7c.png)
![スクリーンショット 2023-04-13 17 15 01](https://user-images.githubusercontent.com/38682085/231697455-677e4584-ccb4-447e-8f3a-459af783f213.png)

2023-04-13 09:23 UTC, ysakajo commented on src/components/Form.vue
> +          { date: number; dateOfWeek: string; foodCost: number; fixedCost: number; id: number }[]
この型をほかの箇所でも使うようになる可能性を考えて、
オブジェクト型をここで直接定義するのではなく、別途定義しましょう。
（この型はHouseholdMainでも使用したいです）

可能であれば、別ファイルに型定義をまとめておくと、
どこで型定義されているかが明確になるのでやってみてほしいです。
（src/util/types.tsとか！）

2023-04-13 09:29 UTC, ysakajo commented on src/components/Form.vue
> +        type: Function,
想定外の関数が呼び出されることを防ぐために、
proptypeを用いてFunctionの引数や返り値を設定しておきましょう！

2023-04-13 09:30 UTC, ysakajo commented on src/components/Form.vue
> +        type: Object as PropType<{ year: number; month: number; day: number }>,
ここも型は別途定義しましょう！

2023-04-13 09:41 UTC, ysakajo commented on src/components/Form.vue
> +      <option value="固定費">固定費</option>
食費、固定費も定数化して管理しましょうか！

今だと複数個所でべた書きされていますが、
情報が１か所に固めることによって、後々コード理解をしやすくなります。
また、例えば交際費など管理する項目を追加したいとなった場合も、
その定数だけを変更すればよくなるので、拡張性が高まります。
（凝集度が高いと言ったりします。）
　

2023-04-13 09:44 UTC, ysakajo commented on src/components/Form.vue
> +      "
実行する関数は１つにして、
その中でsetData(cost); changeTab('table');を実行するようにしましょう。

基本的に@clickに書くのは１行で書けるものにとどめて、
処理自体はscript内で記載してほしいです。
templateはあくまでHTMLを定義する場所なので！

2023-04-13 09:46 UTC, ysakajo commented on src/components/HouseholdMain.vue
> +  const month = reactive([
変数に型を宣言してあげましょう！
今のままだと１つ属性が少なくなっていた場合もエラーにならないため、
バグの原因になる可能性があります。

2023-04-13 09:56 UTC, ysakajo commented on src/components/HouseholdMain.vue
> +    { date: 1, dayOfWeek: '土', foodCost: 0, fixedCost: 0, id: 1 },
30日分のオブジェクトを直接書いていますが、
もっと簡単に記載する方法を考えてみましょう！

for文でも実装可能ですが、記載がシンプルになるので、
練習の意味も込めて、スプレッド構文とmap関数を使ってみてください。
（ここは調べてみて検討がつかなければ、相談してください）

2023-04-13 09:58 UTC, ysakajo commented on src/components/Table.vue
> +      month: [],
想定外の配列が入らないように、型は宣言しておきましょう！

2023-04-13 09:59 UTC, ysakajo commented on src/components/Table.vue
> +      <tr v-for="user in month" :key="user.id">
変数名がuserとなっていますが、ユーザー情報でもないと思うので、
変数名を見直してください。

2023-04-13 10:04 UTC, ysakajo commented on src/components/Table.vue
> +      currentTabName: {},
おそらく使われていないと思うので、削除してください。

2023-04-13 10:21 UTC, ysakajo commented on src/components/Table.vue
> +      };
オプションなので対応するかは時間次第ですが、下記確認お願いします。

この書き方だと内容を理解するのにif分をすべて読む必要があり、
理解に時間がかかってしまいます。
また、ほかの曜日も色を変更したいとなったときにはif文を
その分だけ記載する必要があります。

なので、
曜日の一覧を定義し、そこに色も併せて定義しておく方が望ましいです。
こうすることで、定数を見れば大体どのようなことをしたいかわかり、
変更の際にもこの定数のみ変更すればよくなります。

```
const DAY_OF_WEEKS：DayOfWeek[] = [
  {
    id:1,
    name: '月',
    color: 'bg-gray-100', // こう書けば、tailwindを使用できる
  },
 ・・・
]
```

2023-04-13 10:23 UTC, ysakajo commented on src/components/Table.vue
> +        type: Function,
型をproptypeで定義しましょう！

2023-04-13 10:24 UTC, ysakajo commented on src/components/HouseholdMain.vue
>    const changeTab = (tabName) => {
現状どんな方でも受け取ってしうので、引数（tabName）の型を宣言しておきましょう
changeFormData も同様

2023-04-17 00:54 UTC, dai08 commented on src/components/Form.vue
> +        type: Function,
type: Function as PropType<(cost: string) => string>,
required: true,
を追記しました。

2023-04-17 02:26 UTC, dai08 commented on src/components/Form.vue
> +      <option value="固定費">固定費</option>
初期値を
cost = '1'
// 1=食費、2=固定費
として、食費→1、固定費→2としました。

2023-04-17 02:33 UTC, dai08 commented on src/components/Form.vue
> +      "
setDataメソッドの中にchangeTabメソッドを入れ、
setDataメソッドのみを実行するように変更しました。

2023-04-17 02:50 UTC, dai08 commented on src/components/Table.vue
> +      currentTabName: {},
削除しました。

2023-04-17 03:37 UTC, dai08 commented on src/components/Table.vue
> +      <tr v-for="user in month" :key="user.id">
userをdaysに変更しました。

2023-04-17 03:48 UTC, dai08 commented on src/components/Table.vue
> +        type: Function,
changeTab: {
        type: Function as PropType<(tabName: string) => void>,
        required: true,
      },
      changeFormData: {
        type: Function as PropType<(day: number) => void>,
        required: true,
      },
としました。

2023-04-17 03:49 UTC, dai08 commented on src/components/HouseholdMain.vue
>    const changeTab = (tabName) => {
changeTab: {
type: Function as PropType<(tabName: string) => void>,
required: true,
},
changeFormData: {
type: Function as PropType<(day: number) => void>,
required: true,
},
としました。

2023-04-17 03:51 UTC, dai08 commented on src/components/Table.vue
> +      month: [],
month: {
        type: Array as PropType<
          { date: number; dateOfWeek: string; foodCost: number; fixedCost: number; id: number }[]
        >,
        required: true,
      },
としました。

2023-04-17 09:03 UTC, dai08 commented on src/components/Form.vue
> +          { date: number; dateOfWeek: string; foodCost: number; fixedCost: number; id: number }[]
scriptタグ内でtype Monthを定義し、monthはMonthの配列として定義しました。

2023-04-17 09:07 UTC, dai08 commented on src/components/Form.vue
> +        type: Object as PropType<{ year: number; month: number; day: number }>,
scriptタグ内でtype Dateを定義し、dateのtypeはDateとしました。

2023-04-17 09:07 UTC, dai08 commented on src/components/HouseholdMain.vue
> +    { date: 1, dayOfWeek: '土', foodCost: 0, fixedCost: 0, id: 1 },
const month = [...Array(30)].map((_, index) => ({
    date: index + 1,
    dayOfWeek: ['日', '月', '火', '水', '木', '金', '土'][index % 7],
    foodCost: null,
    fixedCost: null,
    id: index + 1,
  }));
としました。

2023-04-18 06:13 UTC, dai08 commented on src/components/HouseholdMain.vue
> +  const month = reactive([
type.tsでmonthの方を定義しました。

2023-04-18 06:14 UTC, dai08 commented on src/components/Table.vue
> +      };
constant.ts内でDAY_OF_WEEKS配列を定義しました。

2023-04-18 06:32 UTC, ysakajo commented on src/components/HouseholdMain.vue
>    const changeTab = (tabName) => {
子コンポーネントの方ではなく、この関数自体に引数の型を設定してもらいたいです。
指摘がわかりづらくて申し訳ないです！

2023-04-18 06:44 UTC, ysakajo commented on src/components/Form.vue
> +      <option value="固定費">固定費</option>
定数化の意味が伝わっていなかったですね。。。
下記のようなイメージで定義することを伝えたかったです。（型は省略）
```
const COST_TYPE = [
  {id:1, text:'食費'},
  {id:2, text'固定費'},
]
```

上記をv-forで表示すると、
項目が増えた場合もソースコードの変更を最小限にできるので、拡張性が高くなります！

2023-04-18 06:57 UTC, ysakajo commented on src/components/HouseholdMain.vue
> +  const month = reactive([
monthに型Monthが指定されていません。
そもそも<script setup lang='ts'>になっていないので、型の指定ができない？

2023-04-18 06:58 UTC, ysakajo commented on src/components/HouseholdMain.vue
> +    { date: 1, dayOfWeek: '土', foodCost: 0, fixedCost: 0, id: 1 },
`['日', '月', '火', '水', '木', '金', '土']`
上記の部分も定数化した曜日の一覧があるので、それを使いましょう！

2023-04-18 07:00 UTC, ysakajo commented on src/components/Table.vue
> +      month: [],
せっかくMonthを定義したので、ここの型はMonth[]を定義してあげる方がいいです！

2023-04-18 07:03 UTC, ysakajo commented on src/components/Table.vue
> +      <tr v-for="user in month" :key="user.id">
daysだと複数日の情報に見えてしまうので、もう一度変数名を見直してみてください！
細かいですが、変数名は初見の人にとって、理解を早めるためにすごく重要なので！

2023-04-18 07:17 UTC, ysakajo requested changes
レビュー２回目

2023-04-18 07:17 UTC, ysakajo commented on src/components/Form.vue
>    // ユーザーが選択した日付を値として保持。初期値は以下の通り
不要なコメント？

2023-04-18 07:17 UTC, ysakajo commented on src/components/HouseholdMain.vue
> +  // originDay = { date: 3, dayOfWeek: '月', foodCost: null, fixedCost: null, id: 3 };
不要なコメント？

2023-04-18 07:17 UTC, ysakajo commented on src/components/Table.vue
> +            "
指摘漏れてたかもしてないです。。。
この部分も1つの関数にしましょう！

2023-04-18 08:07 UTC, dai08 commented on src/components/Form.vue
>    // ユーザーが選択した日付を値として保持。初期値は以下の通り
削除しました。

2023-04-18 08:08 UTC, dai08 commented on src/components/HouseholdMain.vue
> +  // originDay = { date: 3, dayOfWeek: '月', foodCost: null, fixedCost: null, id: 3 };
削除しました。

2023-04-18 09:06 UTC, dai08 commented on src/components/Form.vue
> +      <option value="固定費">固定費</option>
constant.tsでCOST_TYPEを定義して、Form.vueにimportしました。

2023-04-18 09:09 UTC, dai08 commented on src/components/Table.vue
> +      month: [],
month: {
        type: Array as PropType<Month[]>,
        required: true,
      },
としました。

2023-04-18 09:15 UTC, dai08 commented on src/components/HouseholdMain.vue
>    const changeTab = (tabName) => {
<script>タグに<script lang="ts">と記載し、引数の方を指定しました。

2023-04-18 09:33 UTC, dai08 commented on src/components/HouseholdMain.vue
> +  const month = reactive([
month : Month[]と型指定しました。
その際にfoodCost及びfixedCostで、nullとnumberで型が異なるとエラーが出たので初期値を0としました。

2023-04-19 00:34 UTC, dai08 commented on src/components/HouseholdMain.vue
> +    { date: 1, dayOfWeek: '土', foodCost: 0, fixedCost: 0, id: 1 },
DAY_OF_WEEKSからmap関数で曜日名だけ抽出し、[index % 7]で日付に応じた曜日を抽出しました。

2023-04-19 00:41 UTC, dai08 commented on src/components/Table.vue
> +      <tr v-for="user in month" :key="user.id">
変数をdayにしました。

2023-04-19 00:53 UTC, dai08 commented on src/components/Table.vue
> +            "
changeTabAndFormDataメソッドの中にchangeTabとchangeFormDataを入れました。
templateタグ内にはchangeTabAndFormDataを記載しました。

2023-04-19 02:35 UTC, ysakajo commented on src/components/HouseholdMain.vue
> +  const month = reactive([
タスクではnumber | nullにするように指定されていたので、ここはnullのままにして、型を変更しましょうか！

2023-04-19 02:36 UTC, ysakajo commented on src/components/HouseholdMain.vue
> +    { date: 1, dayOfWeek: '土', foodCost: 0, fixedCost: 0, id: 1 },
youbi.nameとしていますが、分割代入を使うとそのままnameを使えるので、一回試してみてください。
難しそうであれば聞いてください！

2023-04-19 04:02 UTC, ysakajo requested changes

2023-04-19 04:02 UTC, ysakajo commented on src/components/Form.vue
> +        type: Function as PropType<(cost: string) => string>,
引数、返り値を見直してください！

2023-04-19 04:02 UTC, ysakajo commented on src/components/Table.vue
> +        required: true,
使用していないと思うので削除してください。

2023-04-19 04:02 UTC, ysakajo commented on src/components/Table.vue
> +      template
不要な文字列？

2023-04-19 05:55 UTC, dai08 commented on src/components/Form.vue
> +        type: Function as PropType<(cost: string) => string>,
返り値をvoidにしました。

2023-04-19 05:56 UTC, dai08 commented on src/components/Table.vue
> +        required: true,
削除しました。

2023-04-19 05:57 UTC, dai08 commented on src/components/Table.vue
> +      template
削除しました。

2023-04-19 06:05 UTC, dai08 commented on src/components/HouseholdMain.vue
> +    { date: 1, dayOfWeek: '土', foodCost: 0, fixedCost: 0, id: 1 },
DAY_OF_WEEKSの該当番号めの要素を抽出してからnameを取り出しました。

DAY_OF_WEEKS[index % 7].name

2023-04-19 07:29 UTC, dai08 commented on src/components/HouseholdMain.vue
> +  const month = reactive([
number|nullとしました。

2023-04-20 00:15 UTC, merged